### ISSUE TITLE
DTD proxy path no longer valid

### ISSUE THREAD

**Issue by opelsrx** [johanobergman/xml-tv#1]
The old path to [sourceforge](http://xmltv.cvs.sourceforge.net/viewvc/xmltv/xmltv/xmltv.dtd "DTD-file") in the nginx.conf file is no longer valid.  
I found another DTD file that worked for me at [githubusercontent](https://raw.githubusercontent.com/MediaPortal/MediaPortal-1/master/TvEngine3/TVLibrary/TVServer.Base/xmltv/xmltv.dtd).  
  
Maby the best solution would be to download the DTD file instead.  
  
### Bug location:  
   * docker  
      * nginx  
         * nginx.conf row 7 col 8

**Comment by johanobergman** [comment]
Thanks for reporting this! It should be fixed now, let me know if it doesn't work ;)
